/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 8.0 and the Signal Processing Toolbox 6.18.
 *
 * Generated on: 16-May-2014 13:33:26
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 101
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2012b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 101;
const int16_t B[BL] = {
      -23,     -3,      0,      6,     14,     25,     40,     58,     78,
      101,    126,    151,    175,    196,    214,    226,    231,    227,
      213,    188,    152,    105,     48,    -17,    -88,   -162,   -236,
     -305,   -365,   -411,   -440,   -447,   -429,   -382,   -305,   -198,
      -60,    106,    298,    511,    740,    979,   1221,   1458,   1683,
     1888,   2067,   2212,   2320,   2387,   2409,   2387,   2320,   2212,
     2067,   1888,   1683,   1458,   1221,    979,    740,    511,    298,
      106,    -60,   -198,   -305,   -382,   -429,   -447,   -440,   -411,
     -365,   -305,   -236,   -162,    -88,    -17,     48,    105,    152,
      188,    213,    227,    231,    226,    214,    196,    175,    151,
      126,    101,     78,     58,     40,     25,     14,      6,      0,
       -3,    -23
};
