/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 8.0 and the Signal Processing Toolbox 6.18.
 *
 * Generated on: 16-May-2014 16:53:56
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 128
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2012b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 128;
const int16_t B[BL] = {
       27,     15,     17,     19,     19,     17,     12,      4,     -7,
      -21,    -38,    -58,    -81,   -104,   -128,   -150,   -170,   -185,
     -195,   -198,   -193,   -179,   -156,   -124,    -85,    -38,     12,
       65,    117,    165,    206,    236,    254,    257,    242,    210,
      160,     95,     16,    -73,   -167,   -261,   -348,   -424,   -481,
     -513,   -515,   -482,   -413,   -304,   -157,     27,    244,    488,
      754,   1031,   1311,   1585,   1843,   2075,   2272,   2426,   2533,
     2588,   2588,   2533,   2426,   2272,   2075,   1843,   1585,   1311,
     1031,    754,    488,    244,     27,   -157,   -304,   -413,   -482,
     -515,   -513,   -481,   -424,   -348,   -261,   -167,    -73,     16,
       95,    160,    210,    242,    257,    254,    236,    206,    165,
      117,     65,     12,    -38,    -85,   -124,   -156,   -179,   -193,
     -198,   -195,   -185,   -170,   -150,   -128,   -104,    -81,    -58,
      -38,    -21,     -7,      4,     12,     17,     19,     19,     17,
       15,     27
};
